name: chess_versus
description: "Chess tournament manager"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  logging: ^1.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  result_dart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  generate: true